version: 0.2

phases:
  install:
    commands:
      - yum install -y java-latest-openjdk-devel java-latest-openjdk-jmods
  pre_build:
    commands:
      - echo "Installing dependencies..."
      -  java -version
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - aws s3 cp index.html s3://jen-cicd
  post_build:
    commands:
      - echo "Build completed successfully!"
