version: 0.2

phases:
  install:
    commands:
      - dnf install -y nginx
  pre_build:
    commands:
      - echo "Installing dependencies..."
      -  java -version
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
     
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'      

     
