version: 0.2

phases:
  install:
    commands:
      - dnf install -y nginx
  pre_build:
    commands:
      - echo "Installing dependencies..."
      -  java -version
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - aws s3 cp c b  s3://jen-cicd/ 
     
  post_build:
    commands:
      - echo "Build completed successfully!"
#artifacts:
#  files:
#    - '**/*'      

     
