version: 0.2

phases:
  install:
    runtime-versions:
      java: 1.8
  pre_build:
    commands:
      - echo "Installing dependencies..."
      -  java -version
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - aws s3 cp index.html s3://jen-cicd
  post_build:
    commands:
      - echo "Build completed successfully!"
